                    # v
                    # 0
                    # u
                        # v
                            # u
                                    # u
                                    # v
                                # v
                # x
                # y
                    # x
                    # y
