                # u
                # u
                # x
                # 2
                # y
                # 3
                    # x
                    # 2
                        # x
                        # y
